name: test
on: push
jobs: 
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |      
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core 
          ./install.sh $HOME
          cd ..
          $HOME/bin/bats ./test.bats

