name: test
on: push
jobs: 
  test:
    name: ${{ matrix.container }}
    strategy:
      matrix:
        container:
          - 'debian:7'
          - 'debian:testing'
          - 'ubuntu:14.04'
          - 'ubuntu:devel'
          - 'centos:6'
          - 'centos:latest'
        git-version:
          - 1.7.12.4
          - 2.27.0

      fail-fast: false
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v1
    - name: Install git
      run: |
        yum update || apt-get update
        yum install git-${{ git-version }} || apt-get install git-${{ git-version }}

    - name: Install BATS requiremetns
      run: |      
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core && ./install.sh $HOME && cd ..
        git clone https://github.com/ztombol/bats-support
        git clone https://github.com/ztombol/bats-assert

    - name: Run tests
      run: $HOME/bin/bats ./test.bats

